service: example

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: us-west-2
  endpointType: regional

plugins:
  - serverless-wsgi
  - serverless-python-requirements
functions:
  api:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: ANY {proxy+}

custom:
  wsgi:
    app: api.app
  packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux
